---
- hosts: jenkins
  become: yes
  tasks:
    - name: Update all packages
      apt:
        name: '*'
        state: latest
        update_cache: yes

    - name: Install Java for Jenkins
      apt:
        name: openjdk-11-jdk
        state: latest
        update_cache: yes

    - name: Create keyrings directory
      file:
        path: /usr/share/keyrings
        state: directory

    - name: Import keyring for Jenkins
      get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        dest: /usr/share/keyrings/jenkins-keyring.asc
        force: yes
  
    - name: Add Jenkins repository into sources list
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Install Jenkins LTS
      apt:
        name: jenkins
        state: latest
        update_cache: yes

    - name: Start jenkins
      ansible.builtin.systemd:
        name: jenkins
        state: started

    # Docker
    - name: Install prerequisites for Docker repository
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'software-properties-common']
        update_cache: yes
        
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
    
    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
  
    - name: Install Docker CE
      apt:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
        update_cache: yes

    # Enable external connection to Docker
    - name: Create docker.service directory
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory

    - name: Create override for Docker with new option
      ansible.builtin.lineinfile:
        path: /etc/systemd/system/docker.service.d/override.conf
        line: |
           [Service]
           ExecStart=
           ExecStart=/usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:2375
        create: yes

    - name: Restart docker service with daemon-reload
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: docker